# Generated by Django 4.2.11 on 2024-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peope_post',
            new_name='People_post',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
