# Generated by Django 4.2.11 on 2024-11-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_post',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='company_profile',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='people_post',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='people_profile',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='people_profile',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='people_profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='people_profile',
            name='diploma',
        ),
        migrations.AddField(
            model_name='people_profile',
            name='document',
            field=models.FileField(null=True, upload_to='user_document'),
        ),
        migrations.AddField(
            model_name='people_profile',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
