# Generated by Django 4.2.11 on 2024-11-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_user_company_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_post',
            name='deadline',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company_post',
            name='photo',
            field=models.FileField(upload_to='company_post'),
        ),
    ]
