# Generated by Django 4.2.11 on 2024-11-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_apply_job_delete_applay_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_profile',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
