# Generated by Django 4.2.11 on 2024-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_people_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='people_profile',
            name='photo',
        ),
    ]
