# Generated by Django 4.2.11 on 2024-11-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_post',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
